[2025-02-17T22:32:40.190-0600] {processor.py:186} INFO - Started process (PID=20430) to work on /home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:32:40.191-0600] {processor.py:914} INFO - Processing file /home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-17T22:32:40.194-0600] {logging_mixin.py:190} INFO - [2025-02-17T22:32:40.193-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:32:40.198-0600] {logging_mixin.py:190} INFO - [2025-02-17T22:32:40.197-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-17T22:32:40.198-0600] {logging_mixin.py:190} INFO - [2025-02-17T22:32:40.198-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-17T22:32:40.198-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:32:40.210-0600] {processor.py:208} INFO - Processing /home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2025-02-17T22:33:56.421-0600] {processor.py:186} INFO - Started process (PID=21193) to work on /home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:33:56.429-0600] {processor.py:914} INFO - Processing file /home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-17T22:33:56.443-0600] {logging_mixin.py:190} INFO - [2025-02-17T22:33:56.440-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:33:56.447-0600] {logging_mixin.py:190} INFO - [2025-02-17T22:33:56.447-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-17T22:33:56.448-0600] {logging_mixin.py:190} INFO - [2025-02-17T22:33:56.448-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-17T22:33:56.448-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:33:56.461-0600] {processor.py:208} INFO - Processing /home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.048 seconds
[2025-02-17T22:34:56.218-0600] {processor.py:186} INFO - Started process (PID=21829) to work on /home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:34:56.221-0600] {processor.py:914} INFO - Processing file /home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-17T22:34:56.225-0600] {logging_mixin.py:190} INFO - [2025-02-17T22:34:56.224-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:34:56.232-0600] {logging_mixin.py:190} INFO - [2025-02-17T22:34:56.231-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-17T22:34:56.233-0600] {logging_mixin.py:190} INFO - [2025-02-17T22:34:56.233-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-17T22:34:56.234-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:34:56.254-0600] {processor.py:208} INFO - Processing /home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2025-02-17T22:36:00.625-0600] {processor.py:186} INFO - Started process (PID=22483) to work on /home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:36:00.627-0600] {processor.py:914} INFO - Processing file /home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-17T22:36:00.630-0600] {logging_mixin.py:190} INFO - [2025-02-17T22:36:00.629-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:36:00.635-0600] {logging_mixin.py:190} INFO - [2025-02-17T22:36:00.634-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-17T22:36:00.635-0600] {logging_mixin.py:190} INFO - [2025-02-17T22:36:00.635-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-17T22:36:00.636-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:36:00.654-0600] {processor.py:208} INFO - Processing /home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2025-02-17T22:37:02.832-0600] {processor.py:186} INFO - Started process (PID=23060) to work on /home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:37:02.834-0600] {processor.py:914} INFO - Processing file /home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-17T22:37:02.836-0600] {logging_mixin.py:190} INFO - [2025-02-17T22:37:02.835-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:37:02.840-0600] {logging_mixin.py:190} INFO - [2025-02-17T22:37:02.839-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-17T22:37:02.840-0600] {logging_mixin.py:190} INFO - [2025-02-17T22:37:02.840-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-17T22:37:02.840-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:37:02.856-0600] {processor.py:208} INFO - Processing /home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-02-17T22:37:58.594-0600] {processor.py:186} INFO - Started process (PID=23531) to work on /home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:37:58.597-0600] {processor.py:914} INFO - Processing file /home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-17T22:37:58.599-0600] {logging_mixin.py:190} INFO - [2025-02-17T22:37:58.599-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:37:58.607-0600] {logging_mixin.py:190} INFO - [2025-02-17T22:37:58.606-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-17T22:37:58.607-0600] {logging_mixin.py:190} INFO - [2025-02-17T22:37:58.607-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-17T22:37:58.607-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:37:58.620-0600] {processor.py:208} INFO - Processing /home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2025-02-17T22:38:58.680-0600] {processor.py:186} INFO - Started process (PID=24031) to work on /home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:38:58.682-0600] {processor.py:914} INFO - Processing file /home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-17T22:38:58.685-0600] {logging_mixin.py:190} INFO - [2025-02-17T22:38:58.685-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:38:58.694-0600] {logging_mixin.py:190} INFO - [2025-02-17T22:38:58.693-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-17T22:38:58.695-0600] {logging_mixin.py:190} INFO - [2025-02-17T22:38:58.695-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-17T22:38:58.696-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:38:58.721-0600] {processor.py:208} INFO - Processing /home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.053 seconds
[2025-02-17T22:39:59.915-0600] {processor.py:186} INFO - Started process (PID=24543) to work on /home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:39:59.917-0600] {processor.py:914} INFO - Processing file /home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-17T22:39:59.919-0600] {logging_mixin.py:190} INFO - [2025-02-17T22:39:59.919-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:39:59.923-0600] {logging_mixin.py:190} INFO - [2025-02-17T22:39:59.923-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-17T22:39:59.924-0600] {logging_mixin.py:190} INFO - [2025-02-17T22:39:59.924-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-17T22:39:59.924-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:39:59.936-0600] {processor.py:208} INFO - Processing /home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2025-02-17T22:41:00.679-0600] {processor.py:186} INFO - Started process (PID=25047) to work on /home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:41:00.681-0600] {processor.py:914} INFO - Processing file /home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-17T22:41:00.683-0600] {logging_mixin.py:190} INFO - [2025-02-17T22:41:00.683-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:41:00.687-0600] {logging_mixin.py:190} INFO - [2025-02-17T22:41:00.686-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-17T22:41:00.687-0600] {logging_mixin.py:190} INFO - [2025-02-17T22:41:00.687-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-17T22:41:00.688-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-17T22:41:00.700-0600] {processor.py:208} INFO - Processing /home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
