[2025-03-01T23:27:07.341-0600] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-01T23:27:07.401-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: EtlWeather.WeatherAPI manual__2025-03-02T05:27:03.488798+00:00 [queued]>
[2025-03-01T23:27:07.447-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: EtlWeather.WeatherAPI manual__2025-03-02T05:27:03.488798+00:00 [queued]>
[2025-03-01T23:27:07.448-0600] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-01T23:27:07.486-0600] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): WeatherAPI> on 2025-03-02 05:27:03.488798+00:00
[2025-03-01T23:27:07.495-0600] {standard_task_runner.py:72} INFO - Started process 18993 to run task
[2025-03-01T23:27:07.508-0600] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'EtlWeather', 'WeatherAPI', 'manual__2025-03-02T05:27:03.488798+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/dag_1.py', '--cfg-path', '/tmp/tmplgcxcojl']
[2025-03-01T23:27:07.517-0600] {standard_task_runner.py:105} INFO - Job 43: Subtask WeatherAPI
[2025-03-01T23:27:08.577-0600] {task_command.py:467} INFO - Running <TaskInstance: EtlWeather.WeatherAPI manual__2025-03-02T05:27:03.488798+00:00 [running]> on host IMNOTROY.
[2025-03-01T23:27:08.945-0600] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='EtlWeather' AIRFLOW_CTX_TASK_ID='WeatherAPI' AIRFLOW_CTX_EXECUTION_DATE='2025-03-02T05:27:03.488798+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-02T05:27:03.488798+00:00'
[2025-03-01T23:27:08.949-0600] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-01T23:27:08.995-0600] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/dataScience/Projects/Pipeline/airflow/dags/dag_1.py", line 23, in WeatherAPI
    response  = requests.get(url)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/requests/models.py", line 367, in prepare
    self.prepare_url(url, params)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/requests/models.py", line 438, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
[2025-03-01T23:27:09.033-0600] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=EtlWeather, task_id=WeatherAPI, run_id=manual__2025-03-02T05:27:03.488798+00:00, execution_date=20250302T052703, start_date=20250302T052707, end_date=20250302T052709
[2025-03-01T23:27:09.204-0600] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-01T23:27:09.205-0600] {standard_task_runner.py:124} ERROR - Failed to execute job 43 for task WeatherAPI (Invalid URL '': No scheme supplied. Perhaps you meant https://?; 18993)
Traceback (most recent call last):
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/dataScience/Projects/Pipeline/airflow/dags/dag_1.py", line 23, in WeatherAPI
    response  = requests.get(url)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/requests/models.py", line 367, in prepare
    self.prepare_url(url, params)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/requests/models.py", line 438, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
[2025-03-01T23:27:09.265-0600] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-01T23:27:09.324-0600] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-01T23:27:09.340-0600] {local_task_job_runner.py:245} INFO - ::endgroup::
