[2025-03-03T12:22:18.063-0600] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-03T12:22:18.106-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: EtlWeather.WeatherAPI scheduled__2025-03-02T00:00:00+00:00 [queued]>
[2025-03-03T12:22:18.126-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: EtlWeather.WeatherAPI scheduled__2025-03-02T00:00:00+00:00 [queued]>
[2025-03-03T12:22:18.127-0600] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-03T12:22:18.173-0600] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): WeatherAPI> on 2025-03-02 00:00:00+00:00
[2025-03-03T12:22:18.182-0600] {standard_task_runner.py:72} INFO - Started process 4548 to run task
[2025-03-03T12:22:18.187-0600] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'EtlWeather', 'WeatherAPI', 'scheduled__2025-03-02T00:00:00+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/dag_1.py', '--cfg-path', '/tmp/tmpvqqogwtb']
[2025-03-03T12:22:18.192-0600] {standard_task_runner.py:105} INFO - Job 59: Subtask WeatherAPI
[2025-03-03T12:22:18.321-0600] {task_command.py:467} INFO - Running <TaskInstance: EtlWeather.WeatherAPI scheduled__2025-03-02T00:00:00+00:00 [running]> on host IMNOTROY.
[2025-03-03T12:22:18.637-0600] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='EtlWeather' AIRFLOW_CTX_TASK_ID='WeatherAPI' AIRFLOW_CTX_EXECUTION_DATE='2025-03-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-02T00:00:00+00:00'
[2025-03-03T12:22:18.639-0600] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-03T12:22:20.051-0600] {dag_1.py:28} INFO - Data gotten succesfully!
[2025-03-03T12:22:20.052-0600] {python.py:240} INFO - Done. Returned value was: {'dt': 1741026140, 'sunrise': 1741006466, 'sunset': 1741048961, 'temp': 298.06, 'feels_like': 297.42, 'pressure': 1015, 'humidity': 31, 'dew_point': 279.79, 'uvi': 12.08, 'clouds': 20, 'visibility': 10000, 'wind_speed': 0.89, 'wind_deg': 36, 'wind_gust': 2.68, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02d'}]}
[2025-03-03T12:22:20.285-0600] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-03T12:22:20.286-0600] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=EtlWeather, task_id=WeatherAPI, run_id=scheduled__2025-03-02T00:00:00+00:00, execution_date=20250302T000000, start_date=20250303T182218, end_date=20250303T182220
[2025-03-03T12:22:20.389-0600] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-03T12:22:20.428-0600] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-03T12:22:20.441-0600] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-04T12:27:31.414-0600] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-04T12:27:31.572-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: EtlWeather.WeatherAPI scheduled__2025-03-02T00:00:00+00:00 [queued]>
[2025-03-04T12:27:31.639-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: EtlWeather.WeatherAPI scheduled__2025-03-02T00:00:00+00:00 [queued]>
[2025-03-04T12:27:31.640-0600] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-04T12:27:31.743-0600] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): WeatherAPI> on 2025-03-02 00:00:00+00:00
[2025-03-04T12:27:31.755-0600] {standard_task_runner.py:72} INFO - Started process 19747 to run task
[2025-03-04T12:27:31.771-0600] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'EtlWeather', 'WeatherAPI', 'scheduled__2025-03-02T00:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/dataEngineering.py', '--cfg-path', '/tmp/tmpe0sr1km0']
[2025-03-04T12:27:31.777-0600] {standard_task_runner.py:105} INFO - Job 19: Subtask WeatherAPI
[2025-03-04T12:27:32.121-0600] {task_command.py:467} INFO - Running <TaskInstance: EtlWeather.WeatherAPI scheduled__2025-03-02T00:00:00+00:00 [running]> on host IMNOTROY.
[2025-03-04T12:27:32.847-0600] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='EtlWeather' AIRFLOW_CTX_TASK_ID='WeatherAPI' AIRFLOW_CTX_EXECUTION_DATE='2025-03-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-02T00:00:00+00:00'
[2025-03-04T12:27:32.852-0600] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-04T12:27:32.869-0600] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/dataScience/Projects/Pipeline/airflow/dags/dataEngineering.py", line 23, in WeatherAPI
    response  = requests.get(url)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/requests/models.py", line 367, in prepare
    self.prepare_url(url, params)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/requests/models.py", line 438, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
[2025-03-04T12:27:32.894-0600] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=EtlWeather, task_id=WeatherAPI, run_id=scheduled__2025-03-02T00:00:00+00:00, execution_date=20250302T000000, start_date=20250304T182731, end_date=20250304T182732
[2025-03-04T12:27:33.024-0600] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-04T12:27:33.028-0600] {standard_task_runner.py:124} ERROR - Failed to execute job 19 for task WeatherAPI (Invalid URL '': No scheme supplied. Perhaps you meant https://?; 19747)
Traceback (most recent call last):
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/dataScience/Projects/Pipeline/airflow/dags/dataEngineering.py", line 23, in WeatherAPI
    response  = requests.get(url)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/requests/models.py", line 367, in prepare
    self.prepare_url(url, params)
  File "/home/dataScience/Projects/Pipeline/venv/lib/python3.10/site-packages/requests/models.py", line 438, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
[2025-03-04T12:27:33.103-0600] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-04T12:27:33.184-0600] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-04T12:27:33.208-0600] {local_task_job_runner.py:245} INFO - ::endgroup::
