[2025-03-04T12:27:26.480-0600] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-04T12:27:26.674-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: EtlWeather.SendMessage scheduled__2025-02-20T00:00:00+00:00 [queued]>
[2025-03-04T12:27:26.780-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: EtlWeather.SendMessage scheduled__2025-02-20T00:00:00+00:00 [queued]>
[2025-03-04T12:27:26.785-0600] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-04T12:27:26.984-0600] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): SendMessage> on 2025-02-20 00:00:00+00:00
[2025-03-04T12:27:27.002-0600] {standard_task_runner.py:72} INFO - Started process 19670 to run task
[2025-03-04T12:27:27.055-0600] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'EtlWeather', 'SendMessage', 'scheduled__2025-02-20T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/dataEngineering.py', '--cfg-path', '/tmp/tmpx1_mva4o']
[2025-03-04T12:27:27.113-0600] {standard_task_runner.py:105} INFO - Job 8: Subtask SendMessage
[2025-03-04T12:27:27.725-0600] {task_command.py:467} INFO - Running <TaskInstance: EtlWeather.SendMessage scheduled__2025-02-20T00:00:00+00:00 [running]> on host IMNOTROY.
[2025-03-04T12:27:28.598-0600] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='EtlWeather' AIRFLOW_CTX_TASK_ID='SendMessage' AIRFLOW_CTX_EXECUTION_DATE='2025-02-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-20T00:00:00+00:00'
[2025-03-04T12:27:28.617-0600] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-04T12:28:47.614-0600] {job.py:229} INFO - Heartbeat recovered after 50.12 seconds
[2025-03-04T12:29:13.939-0600] {job.py:229} INFO - Heartbeat recovered after 29.28 seconds
[2025-03-04T12:31:10.493-0600] {job.py:229} INFO - Heartbeat recovered after 63.21 seconds
[2025-03-04T12:32:16.960-0600] {job.py:229} INFO - Heartbeat recovered after 96.59 seconds
[2025-03-04T12:32:29.380-0600] {python.py:240} INFO - Done. Returned value was: Done!
[2025-03-04T12:32:30.883-0600] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-04T12:32:30.895-0600] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=EtlWeather, task_id=SendMessage, run_id=scheduled__2025-02-20T00:00:00+00:00, execution_date=20250220T000000, start_date=20250304T182726, end_date=20250304T183230
[2025-03-04T12:32:31.383-0600] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-04T12:32:31.625-0600] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-04T12:32:31.630-0600] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-04T12:32:31.644-0600] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
